- blocks/header/header.css
- blocks/hero/hero.css
- scripts/aem.js
- styles/styles.css
Test URLs:
- After: https://inital-setup--creditacceptance--aemsites.aem.page/
Testing criteria - what should the reviewer look for in your PR:
> Section intial

- blocks/marquee/marquee.css
- scripts/scripts.js
This is a quick fix to allow the marquee to display on the homepage. There was a conflict w/ the .hero headline selector and one extra style needed to override default style.css `picture {display: block}`
Fix /NA
Test URLs:
- After: https://rparrish-hero-fix--creditacceptance--aemsites.aem.page/
Check the links above and make sure the marquee at the top looks good. 👌
> Remove buildHero() and update marquee to fix style on bg cover image

- helix-query.yaml
Test URLs:
- After: https://article-index--creditacceptance--aemsites.aem.page/
Testing criteria - what should the reviewer look for in your PR:
> helix-query.yaml

- blocks/marquee/marquee.css
- blocks/marquee/marquee.js
- styles/styles.css
Adjusted marquee to have better viewport support and addressed bugs:
1. 3rd button not showing up.
- Was an authoring issue - adjusted page to correct (this can happen when there is a bold styling on an empty space in between links.
2. way to control height - Adjusted the marquee to have better viewport support. 
- Set a default height of `470` and a optional variant `heigh-auto` to allow content to declare height
4. Color config on the subtitle not picking dark text color instead of white (as per the config) 
- Adjusted marquee label to auto detect dark context and removed the 'dark' column in the palette sheet
1) label underline had gap on some browsers (edge)
Fix [#131](https://github.com/aemsites/creditacceptance/issues/131) && …
> #131 && #122 Marquee bugs

- blocks/cards/cards.js
- blocks/testimonials/testimonials.css
- blocks/testimonials/testimonials.js
Fix #3 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/testimonials
- After: https://smalla-testimonials--creditacceptance--aemsites.aem.page/drafts/smalla/testimonials
Testing criteria - Compare against testimonials https://www.creditacceptance.com/, https://www.creditacceptance.com/car-buyers
> #3 - add testimonials block

- blocks/footer/footer.css
Remove extra spacing between card and
Fix #157 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane/cosigner
- After: https://fix-157--creditacceptance--aemsites.aem.page/car-buyers/express-lane/cosigner
_More Testing urls found in #157, please use appropriate branch to test all of those pages_
Testing criteria - Details in issue #157
> #157 - fix extra gap

- blocks/calculator/calculator.css
- blocks/calculator/calculator.js
- styles/styles.css
This PR add calculator block. There are two variants - default is car estimate calculator and `monthly` variant is monthly payment calculator, similar to the original flow used in current CA. 
Fix #22
Test URLs:
Monthly Payment Calculator:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/monthly-car-payment-calculator
- After: https://smalla-calculator--creditacceptance--aemsites.aem.page/drafts/smalla/monthly-car-payment-calculator
Car Price Estimate:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/estimated-car-price
- After: https://smalla-calculator--creditacceptance--aemsites.aem.page/drafts/smalla/estimated-car-price
Testing criteria - To compare against https://www.creditacceptance.com/car-buyers/car-price-calculator …
> #22 - Calculator

- blocks/anchor-links/anchor-links.css
- blocks/anchor-links/anchor-links.js
- styles/styles.css
Created anchor-links block and styles
Fix #[228](https://github.com/aemsites/creditacceptance/issues/228)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/how-it-works
- After: https://rparrish-anchor-links--creditacceptance--aemsites.aem.page/dealers/how-it-works
Testing criteria - Check the links above w/ the live site and make sure all looks right. 
https://www.creditacceptance.com/dealers/how-it-works#programs
> #228 - 🆕 [anchor-links] block

- blocks/cards/cards.css
Fix #263 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/related-cards-v2
- After: https://smalla-fix--creditacceptance--aemsites.aem.page/drafts/smalla/related-cards-v2
Testing criteria - what should the reviewer look for in your PR:
> #263 - fix card images for feature-tall, feature-wide

- blocks/accordion/accordion.js
Use the id as hash for the link that will open the accordion item.
Fix #119 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/faq/accordion-expand
- After: https://smalla-accordion-expand--creditacceptance--aemsites.aem.page/drafts/smalla/faq/accordion-expand
> #119 - expand accordion with id

- helix-sitemap.yaml
- scripts/aem.js
Just providing the icon names as alt text.
Fix #317 
Test URLs:
- After: https://sitemap--creditacceptance--aemsites.aem.page/
> Accessibility: Icons Alt text 

- blocks/cards/cards.css
Fix #327 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers
- After: https://nrego-btn-alignment--creditacceptance--aemsites.aem.page/car-buyers
Testing criteria - should match live site: https://www.creditacceptance.com/car-buyers
> [#327] Resource card button alignment

- blocks/columns/columns.css
- blocks/columns/columns.js
Fix #335
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/grow-your-dealership/sp
- After:https://smalla-columns-stats--creditacceptance--aemsites.aem.page/campaign/grow-your-dealership/sp
Testing criteria - https://www.creditacceptance.com/campaign/grow-your-dealership/sp#nums_home_heading
> #335 - columns (stats-small) variant

- blocks/anchor-links/anchor-links.css
- blocks/embed/embed.css
- blocks/embed/lite-vimeo-embed/lite-vimeo-embed.js
- blocks/embed/lite-vimeo-showcase/lite-vimeo-showcase.js
- blocks/header/header.js
- blocks/video-carousel/video-carousel.css
- libs/utils/decorate.js
- scripts/scripts.js
fix: #354 
Test URLs:
- After: https://ally--creditacceptance--aemsites.aem.page/
- Before: https://main--creditacceptance--aemsites.aem.page/customers
- After: https://ally--creditacceptance--aemsites.aem.page/customers
> Accessibility fixes + anchor links alignment

- blocks/calculator/calculator.js
- styles/fonts.css
Fix #342 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/customers/make-a-payment
- After: https://smalla-fonts-cls--creditacceptance--aemsites.aem.page/customers/make-a-payment
Testing criteria - CLS issue
> #342 - CLS on page Make your Payment

- libs/utils/decorate.js
Fix #407 
Test URLs:
- After: https://btn-fix--creditacceptance--aemsites.aem.page/
> Bold text disappears in any block

- blocks/accordion/accordion.js
- blocks/table/table.css
Fix #404 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/customers/faq#are-there-fees-associated-with-the-different-payment-options
- After: https://smalla-404--creditacceptance--aemsites.aem.page/customers/faq#are-there-fees-associated-with-the-different-payment-options
Testing criteria - Spacing at the end of table, within accordion and when two tables are placed together. Expanding of accordion with the id of accordion.
> #404 - Add table margins, fix accordion expand 

- blocks/header/header.css
- blocks/header/header.js
- Addressed the issue reported by CreditAcceptance. They use computers that have a mouse and are touchscreen. 
- Addressed brand logo margin
Fix [#344](https://github.com/aemsites/creditacceptance/issues/344)
Test URLs:
- After: https://rparrish-header-d--creditacceptance--aemsites.aem.page/
Testing criteria - Hard to test unless you have the mentioned device. Check there is a 1rem margin after logo on desktop
> Main nav - Hover not working on some devices that are `deviceType === touchscreen  && !touchDevice`

- blocks/columns/columns.css
- libs/utils/decorate.js
- scripts/scripts.js
- styles/styles.css
Test URLs:
- After: https://btn-fix--creditacceptance--aemsites.aem.page/
> Loading launch eager

- blocks/embed/embed.js
- blocks/jon-form/jon-form.js
- libs/utils/utils.js
Add environment specific config- test, qa and production. 
Fix #280
Test URLs:
- Before: https://smalla-env--creditacceptance--aemsites.aem.page/dealers/join-our-network
- After: https://smalla-env--creditacceptance--aemsites.aem.page/dealers/join-our-network
Testing criteria - Config coming from global sheet for different env.
> #280 - Environment Configs 

- blocks/header/header.css
Fix #438
Test URLs:
- After: https://smalla-438--creditacceptance--aemsites.aem.page/
Testing criteria - header submenu color
> #438 - fix header submenu color

- blocks/columns/columns.css
- blocks/footer/footer.css
Fix #446 
Test URLs:
- After: https://smalla-fix--creditacceptance--aemsites.aem.page/
Testing criteria - border right/line in mobile footer
> #446 - remove line in footer mobile

- blocks/header/header.js
- Fixed nav so mobile hamburger works w/ the getEnvConfig param
Fix https://github.com/aemsites/creditacceptance/issues/492
Test URLs:
- After: https://rparrish-nav-bug--creditacceptance--aemsites.aem.page/
Testing criteria - Check that the account icon still uses the getEnvConfig param and that the hamburger still opens the mobile menu
> Fixed - User cannot open Top Navigation

- blocks/cards/cards.js
- blocks/feed/feed.css
Fix incorrect date style in feed.
Fix #499 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane
- After: https://smalla-499--creditacceptance--aemsites.aem.page/car-buyers/express-lane
Testing criteria - Look for "Long-Lasting Vehicles of 2021" card title under "Car Buying Tips and Guides" category.
> #499 - Fix incorrect date style in feed

- blocks/cards/cards.css
Fix #516 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane/financial-education
- After: https://smalla-516--creditacceptance--aemsites.aem.page/car-buyers/express-lane/financial-education
> #516 - add gap in slider-mobile for cards

- blocks/cards/cards.css
- blocks/footer/footer.css
Fix #560  
Test URLs:
- After: https://cards-fix--creditacceptance--aemsites.aem.page/
> Footer fix

- blocks/accordion/accordion.css
- blocks/columns/columns.css
Test URLs:
- After: https://accordionfix--creditacceptance--aemsites.aem.page/
> Accordionfix
