aemsites/creditacceptance

blocks/awards/awards.css, blocks/awards/awards.js, styles/styles.css
This PR includes a new block for _awards_ to support the designs in current Credit Acceptance site. 
Fix #28
Test URLs:
Before: https://main--creditacceptance--aemsites.aem.page/drafts/nrego/awards
After: https://nrego-awards--creditacceptance--aemsites.aem.page/drafts/nrego/awards
Testing criteria: compare awards sections on the current Credit Acceptance site - https://www.creditacceptance.com/about, https://www.creditacceptance.com/careers
=> [#28] Block: awards

blocks/table/table.css, blocks/table/table.js
Currently, there isn't a way for us to render tables because all tables are transformed into blocks. So, adding `table` block to render the actual table that can be used for CA site. 
Importing `table` block  from [**AEM Block Collection**](https://github.com/adobe/aem-block-collection/tree/main/blocks/table)
Fix: #75 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/fragments/smalla/faqs/managing-text-alerts 
- After: https://table--creditacceptance--aemsites.aem.page/fragments/smalla/faqs/managing-text-alerts
Example of all variants: https://sidekick-library--aem-block-collection--adobe.aem.page/block-collection/table
=> #75 - Add table block 

styles/styles.css
I realized after I merged the section background stuff that there was a lost style on button.primary. Oops, my bad
Fix n/a
Test URLs:
- After: https://rparrish-btn-fix--creditacceptance--aemsites.aem.page/
Testing criteria - Take a look at the homepage and hover over a button primary. Notice there is no background color change. :(
=> Button.Primary - quick fix for styles

blocks/tabs-metadata/tabs-metadata.css, blocks/tabs-metadata/tabs-metadata.js, blocks/tabs/tabs.css, blocks/tabs/tabs.js, styles/styles.css
I updated the tabs block to use sections as it's tab-content.
Here's the document relationship example. 
- Tab-list is a list in the first block row
- Id key is a required tabID to associate the related `tab-metadata` with the following params
-- key: tabID
-- section: Index of tab-list association
(Im open to different names, just LMK)
I am using a new `tabs-metadata` table for this association. I had originally tried using `section-metadata tab: {tabId}, {index}` but I ran into race conditions where the section-meta is removed and the blocks vs section decorators are decorated async so the tabs block query selectors weren't reliable. This could be refactored w/ a section promise, but It felt intrusive as a site whole for this feature. LMK if you have any thoughts on the approach I took …
=> #11 Tabs block w/ Sections

blocks/header/header.css, blocks/header/header.js, blocks/tabs/tabs.css
I refactored the nav to use a [single file](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BAF3F3792-C5D1-401F-B467-A949F78964CF%7D&file=nav1.docx&action=default&mobileredirect=true) and adjusted the scripts and styles to accommodate all viewports.  
I have an [index.html doc](https://adobe.sharepoint.com/sites/HelixProjects/_layouts/15/doc.aspx?sourcedoc={7e9c0036-dc0d-43ee-8225-f28993ef1cf3}&action=edit) in my drafts directory with the metadata table pointing to this 'nav-new'. This will look wonky on other pages FYI
Fix [#50](https://github.com/aemsites/creditacceptance/issues/50)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/
- After: https://rparrish-menu--creditacceptance--aemsites.aem.page/drafts/rparr …
=> #50 - Main navigation - Mobile and Desktop in one doc. No duplicate links/code

blocks/cards/cards.css, blocks/cards/cards.js, styles/styles.css
This PR extends features to current `Card` block with `rounded`, `gap-{size}`, `{number}-ups`
Fix #23
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/cards
- After: https://smalla-cards--creditacceptance--aemsites.aem.page/drafts/smalla/cards
=> #23 - add card block variations

libs/utils/utils.js, scripts/ffetch.js, tools/tagger/tagger.js
Reverted the ffetch.js lib to original file and passed `sheet` param as [documented](https://github.com/adobe/ffetch)
Fix N/A
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/tools/tagger/index.html
- After: https://rparrish-fix-ffetch--creditacceptance--aemsites.aem.page/tools/tagger/index.html
Testing criteria - Have a look at the above URL's they should be the same. The after should still load the tagger and palette ffetch'd data
=> Revert ffetch.js

blocks/cards/cards.css, blocks/cards/cards.js, blocks/related-cards/related-cards.css, blocks/related-cards/related-cards.js
This allows authors to use urls to create related cards.
Fix #111 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/related-cards
- After: https://smalla-related-cards--creditacceptance--aemsites.aem.page/drafts/smalla/related-cards
Testing criteria - Compare against related cards in https://www.creditacceptance.com/
=> #111 - add related-cards block

blocks/header/header.css, blocks/header/header.js, styles/styles.css
The following has been addressed in the main menu
1. Remove default ::marker arrows on menu details element on IOS (see below)
2. Increase spacing/gap on nav about-us, careers items
3. Adjust nav links color to match site
4. On the mobile menu, when the nav is open, the account icon and logo shouldn't display
5. Clicking outside the nav on mobile and desktop view should close/collapse its respective nav list
Fix [#146](https://github.com/aemsites/creditacceptance/issues/146)
**Test URLs:**
- After: https://rparrish-menu-update--creditacceptance--aemsites.aem.page/
**Testing criteria**
Test the above list is remedied
Bonus - updated our style.css link/button colors from `hsl` to `oklch` and fixed the secondary hover style to …
=> #146 Menu Updates

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
1) Scoped `ol` list style to `.ca-list ol` and added class to [columns] block on init().
2) Added a variant `(vertical-center)` to center content in columns if authored
Fix [#124](https://github.com/aemsites/creditacceptance/issues/124) && [#128](https://github.com/aemsites/creditacceptance/issues/128)
**Test URLs:**
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/columns
- After: https://rparrish-col-update--creditacceptance--aemsites.aem.page/drafts/rparrish/columns
**Testing criteria** 
Have a look the `ol` list is scoped only to parent class container. 
The test page includes an example w/ the added `vertical-center` variant. Confirm the content/media is in the middle of col vertical space.
=> Column block updates

blocks/columns/columns.css
Added styles to support an additional `stats` variant on the [columns] block for the HP.
`Columns (stats)`
Fix [#47](https://github.com/aemsites/creditacceptance/issues/47)
Draft URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/grid-stats
- After: https://rparrish-col-stats--creditacceptance--aemsites.aem.page/drafts/rparrish/grid-stats
Home URLs:
- After: https://rparrish-col-stats--creditacceptance--aemsites.aem.page/
Testing criteria - Check these look good in all viewports and match the original site. (ours has a little better alignment, btw)
=> #47 Column stats

blocks/cards/cards.css, blocks/cards/cards.js
Fix for icons on the resource cards not being left aligned. 
Fix #145 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane/5-ways-to-build-or-reestablish-your-credit-history
- After: https://nrego-card-icons--creditacceptance--aemsites.aem.page/car-buyers/express-lane/5-ways-to-build-or-reestablish-your-credit-history
When the resource card is set to be left aligned, the icons should line up with the content on the left hand side.
=> [#145] Card: Resources, images left aligned fix

blocks/cards/cards.css, blocks/image-text-overlay/image-text-overlay.css, blocks/image-text-overlay/image-text-overlay.js, blocks/slider/slider.css, blocks/testimonials/testimonials.css, blocks/testimonials/testimonials.js, libs/utils/decorate.js
- Added 🆕  [image-text-overlay] block 
- Added a shared initSlider() function in `decorate.js` and supporting `slider.css` styles
- Added 'slider-mobile' variant options on [image-text-overlay] and [testimonials] blocks
Fix [#88](https://github.com/aemsites/creditacceptance/issues/88)
Test URLs:
- Before: http://main--creditacceptance--aemsites.aem.page/drafts/rparrish/card-sliders
- After: https://rparrish-img-txt-overlay--creditacceptance--aemsites.aem.page/drafts/rparrish/card-sliders
Check the test url in both mobile and desktop to make sure the UI and look match the [live site HP](https://www.creditacceptance.com/) usage. (refresh is needed for slider to init.)
This pattern is going to be used on many of the …
=> #88 Mobile slider for testimonials and new [image-text-overlay] block. 

blocks/carousel/carousel.css, blocks/carousel/carousel.js
Update for carousel block: 
- Slides per view can be set for desktop or mobile 
- Arrows hidden if total slide length is equal to or slides per view
- Arrow placement (center with image) 
Fix #193 #194 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/nrego/carousel
- After: https://nrego-carousel-update--creditacceptance--aemsites.aem.page/drafts/nrego/carousel
=> [#193, #194] Carousel slides per view on mobile and arrow placement

blocks/columns/columns.css, blocks/columns/columns.js
This piece of content is very different in mobile that cannot be solved with columns or any other block. So, adding a variant to `column` block called `calculation` to support this.
Fix #283
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/feb-19/campaign/grow-your-dealership/sp
- After: https://smalla-columns-calculation--creditacceptance--aemsites.aem.page/drafts/feb-19/campaign/grow-your-dealership/sp
Testing criteria - https://www.creditacceptance.com/campaign/grow-your-dealership
=> #283 - add columns (calculation) variant

blocks/modal/modal.css
Fix #302
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/resources
- After: https://nrego-modal-scroll--creditacceptance--aemsites.aem.page/car-buyers/resources
Testing criteria - the user should not be scrolled to the top of the page when a modal is opened
=> [#302] Modal shouldn't scroll to top on open

blocks/fragment/fragment.js, libs/utils/decorate.js, styles/styles.css
Refactored the grid sections to address library usage
- Also included a fix to address section-outer overflow: hidden for horizontal scroll when media-unbound is added. 
Fix /na
Libs URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/tools/sidekick/blocks/section
- After: https://rparrish-grid-library--creditacceptance--aemsites.aem.page/tools/sidekick/blocks/section
Grid Draft URLs: ⚠️ Regression testing ⚠️ 
- Before:https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/grid-stats
- After: https://rparrish-grid-library--creditacceptance--aemsites.aem.page/drafts/rparrish/grid-stats
Testing criteria - Check that the library page loads on my branch and the respective grid sections look as advertised. (Aka the section in Libs url w/ a gray background)
=> Grid section-metadata broken in library view

blocks/header/header.css, blocks/header/header.js
Hiding header elements on mobile for alternative nav with just logo present. 
Fix #51 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/200-promo-rewards
- After: https://nrego-simple-header--creditacceptance--aemsites.aem.page/campaign/200-promo-rewards
Testing criteria - should match behaviour of current site: https://www.creditacceptance.com/campaign/200-promo-rewards
=> [#51] Logo only header - hide additional items on mobile

blocks/header/header.css, styles/styles.css
- Fixed default content wrapper to be centered on tablet viewport
- Addressed header issue on expanded mobile (background white color wasn't flowing thru content) 
Fix [#233](https://github.com/aemsites/creditacceptance/issues/233)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/customers
- After: https://rparrish-fixes--creditacceptance--aemsites.aem.page/customers
- Open the pages above before/after and make sure the section `download the credit acceptance mobile app` is centered and not on the edge of the page on a tablet viewport `<578 && >968`
- Size your browser to below desktop `>968` and toggle the menu hamburger. The white should show behind nav content on after view
=> Minor fixes - mobile header bg, default-content wrapper margin auto

styles/styles.css
Added a style for section-metadata to opt in to `overflow: visible;`
Fix [#330](https://github.com/aemsites/creditacceptance/issues/330)
Test URLs:
- Before: https://main--creditacceptance--aemsites.hlx.page/campaign/prequalify
- After: https://rparrish-section-steps--creditacceptance--aemsites.hlx.page/campaign/prequalify
Testing criteria - make sure the steps (big numbers) in the section below the marquee are visible and over the marquee area.
=> added overflow-visible to section styles

blocks/header/header.js, blocks/quick-links/quick-links.js, styles/styles.css, templates/blog-page/blog-page.css
Update a few flagged accessibility issues
- Blog header color
- default link text to brand color
- aria-labels updates on main nav and quick-links
Fix [#210](https://github.com/aemsites/creditacceptance/issues/210)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/the-lot/working-with-first-time-car-buyers-with-no-credit
- After: https://rparrish-accessibilty--creditacceptance--aemsites.aem.page/dealers/the-lot/working-with-first-time-car-buyers-with-no-credit
Testing criteria - Do an accessibility check to validate changes have a positive impact. 
FYI - Im seeing some false flags using the browser extension 'SiteImprove Accessibility Checker' - specifically it thinks the links are white. 🤷  LMK if you see any other glaring ones.
=> #210 minor accessibility improvements

blocks/marquee/marquee.css, scripts/scripts.js, styles/styles.css
- Added load marquee image eager 
-- FYI, The defatult aem.js script looks for the first section single image. Which we have quick-links as the first section w/ no image so the marquee was missed
- Added marquee variant `vertical-center` to set this default on content mobile up. 
-- (no `-mobile` suffix needed since it's already vertically centered by default on desktop)
Fix [#341](https://github.com/aemsites/creditacceptance/issues/341) | [#319](https://github.com/aemsites/creditacceptance/issues/319)
1) Test URLs (eager loading):
- After: https://rparrish-marquee-bug--creditacceptance--aemsites.aem.page/
2) Test URLs (vertical-center):
- Before: https://main--creditacceptance--aemsites.aem.page/about/contact-us
- After: …
=> Marquee fixes - eager image load, `vertical-center` variant

blocks/header/header.css, blocks/text/text.css, styles/styles.css
- Fixed the grid so the `span-*` elements only apply on desktop up
-- This was causing some issues w/ using a gap w/ grids on mobile/tablet - See the before link form section
- Added options for bg images on a text block - @jordanpetersen27 asked for this as a general option when [prototyping pages](https://rparrish-text-bg--creditacceptance--aemsites.aem.page/campaign/bhph-v2). 
Fix [#297](https://github.com/aemsites/creditacceptance/issues/297)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/bhph
- After: https://rparrish-text-bg--creditacceptance--aemsites.aem.page/campaign/bhph
Testing criteria - Check the grid elements take up full span-12 on mobile VP.
=> #297 - Fix grid and add text block bg image options

blocks/accordion/accordion.css, blocks/columns/columns.css, blocks/columns/columns.js, blocks/quick-links/quick-links.css, libs/utils/decorate.js, scripts/delayed.js, scripts/googletagmanager-worker.js, styles/styles.css
- accordion header icon alignment
- adjusted column icon-elem styles and logic to display icon margin in p and header tags
- added option to section-metadata: grid | span-auto - (see the customers `V2` page w/ a single quick-link button/title)
- fixed `btn.blue` brand colors
Fix 
- Icon wrapping for `<p>` - [357](https://github.com/aemsites/creditacceptance/issues/357)
- UL accessiblity - [#366](https://github.com/aemsites/creditacceptance/issues/366)
- Big-icons - [373](https://github.com/aemsites/creditacceptance/issues/373)
Customers pg: (column-icons)
- Before: https://main--creditacceptance--aemsites.aem.page/customers
- After: https://rparrish-column-icons--creditacceptance--aemsites.aem.page/customers
Contact Us pg: (grid-auto, column-icons) - I added a V2 page w/ updated …
=> Columns w/ Icons 

blocks/tabs/tabs.css, libs/utils/decorate.js, styles/styles.css
When an author adds multiple buttons on the same line, It is easy to overlook the 'styled' space between items resulting in them having a shared element and the button decorator will remove nth(2+) children. 
- Fixed button logic to address when authoring multiple buttons that share a decorator tag `<span> || <em>`
Fix [#347](https://github.com/aemsites/creditacceptance/issues/347)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/inline-buttons
- After: https://rparrish-btns--creditacceptance--aemsites.aem.page/drafts/rparrish/inline-buttons
Regression URLS
- After: https://rparrish-btns--creditacceptance--aemsites.aem.page/
Testing criteria - Check that all the authored buttons show on the …
=> Button decorator fix to address missing buttons

blocks/cards/cards.css, blocks/cards/cards.js
Updated logic to allow any header (h2-h6) in a card and if there are 2, the first one becomes the card-intro in `grid -> <li>` but outside of .card for (resources) type. 
Fix [#367](https://github.com/aemsites/creditacceptance/issues/367)
Draft URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/cards-resources
- After: https://rparrish-cards-htag--creditacceptance--aemsites.aem.page/drafts/rparrish/cards-resources
Live URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/200-promo
- After: https://rparrish-cards-htag--creditacceptance--aemsites.aem.page/campaign/200-promo
Testing criteria - Author should expect any header to be author able in a card block. If using the variant (resources) and authored w/ 2 headers, The first one will …
=> Cards allow any header h2-h6

blocks/columns/columns.css, libs/utils/decorate.js, styles/styles.css
An option to reverse grid on mobile.
We already have a col-mobile-reverse for columns. extending that to grids.
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/kailas/join-our-network
- After: https://btn-fix--creditacceptance--aemsites.aem.page/drafts/kailas/join-our-network
=> Grid reverse on mobile

blocks/accordion/accordion.css, blocks/footer/footer.css
Remove footer spacings, also fixes spacing for `li` items used for links
Fix #433 
Test URLs:
- After: https://smalla-433--creditacceptance--aemsites.aem.page/
Testing criteria - Footer spacings
For regression - Spacing between FAQ headings - https://smalla-433--creditacceptance--aemsites.aem.page/customers/faq
=> #433 - fix footer spacing issues

blocks/columns/columns.css
Fix `big-icons` variant of columns on mobile
Fix #390 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/smalla/big-icons
- After: https://smalla-390--creditacceptance--aemsites.aem.page/drafts/smalla/big-icons
Page `/careers` - https://smalla-390--creditacceptance--aemsites.aem.page/careers 
Testing criteria - On mobile screen, big icons shouldn't cause layout issue.
For Regression - 
- https://smalla-390--creditacceptance--aemsites.aem.page
- https://smalla-390--creditacceptance--aemsites.aem.page/dealers/join-our-network
=> Fix #390 - fix big icons on mobile

blocks/columns/columns.css, blocks/header/header.css, blocks/marquee/marquee.css, blocks/marquee/marquee.js, styles/styles.css
- Fixed the overlap by setting nav height w/ no t/b padding. 
- Added max-width-90, max-width-90-desktop to marquee variant list
- Added function to make marquee title border same width as header
- Added bottom margin for columns .media row on mobile
Fix [#441](https://github.com/aemsites/creditacceptance/issues/441) 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/how-it-works
- After: https://rparrish-header-overflow--creditacceptance--aemsites.aem.page/car-buyers/how-it-works
- size down to mobile and compare screens w/ before/after, confirm the top of the marquee graphic is showing and not covered by the nav. 
- Check the marquee title border goes same width as the heading, same on resize
- Look at the columns in mobile and confirm …
=> Marquee image and top nav overlapping

blocks/marquee/marquee.css
Added `max-width-90, max-width-90-desktop` to marquee variant list
Fix [#441](https://github.com/aemsites/creditacceptance/issues/441#issuecomment-2707439850)
Test URLs:
Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/how-it-works
After: https://rparrish-mq-max-width--creditacceptance--aemsites.aem.page/car-buyers/how-it-works
Testing criteria - max-width-90 etc was somehow omitted from past PR. Please verify it is added back in
=> Marquee - max-width-90 added

blocks/columns/columns.css, styles/styles.css
- removed gap on columns.divided-list to rely on variant or default
- added gap 5,6 …to columns and section:grid
Fix [#451](https://github.com/aemsites/creditacceptance/issues/451)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/prequalify
- After: https://rparrish-col-gap--creditacceptance--aemsites.aem.page/campaign/prequalify
Testing criteria - check the page has the authored gap variant `gap-4`
=> Gap on columns.divided-list not respecting gap variant, added gap 5,6 to columns and section:gap

blocks/columns/columns.css, blocks/text/text.css
- Added variant to text block `text (icon-margin)` to support this style in a text block to group icon rows and preceding content. 
- removed the reduced margin on `columns .icon-elm .divider-thin-blue-dot` for consistency
Fix [#428](https://github.com/aemsites/creditacceptance/issues/428) && [#427](https://github.com/aemsites/creditacceptance/issues/427)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/columns1
- After: https://rparrish-cols-icons--creditacceptance--aemsites.aem.page/drafts/rparrish/columns1
**Page urls in question**
Before
https://main--creditacceptance--aemsites.aem.page/about/contact-us
https://main--creditacceptance--aemsites.aem.page/car-buyers/how-it-works
After
https://rparrish-cols-icons--creditacceptance--aemsites.aem.page/ab …
=> Columns w/ icons - Text align above icons, consistent divider-blue-line

blocks/marquee/marquee.js
Used aem.js `createOptimizedPicture()` method to pass in optional breakpoint size param for our mobile images on marquee. 
Fix [#395](https://github.com/aemsites/creditacceptance/issues/395)
Test URLs:
before: https://main--creditacceptance--aemsites.aem.page/
after: https://rparrish-mobile-img--creditacceptance--aemsites.aem.page/
Testing criteria - check the inspector network tab to confirm the mobile image is smaller.
=> Performance improvement - mobile images on marque

blocks/header/header.css, blocks/header/header.js, blocks/marquee/marquee.css
- Added new variants to the marquee block `height-medium` && `height-large` which = `550px` && `700px` height for desktop up
- Addressed alignment issue on nav .logo-only so it's is justified left
Fix 
- marquee medium/large [#458](https://github.com/aemsites/creditacceptance/issues/458)
- logo-only alignment [#458](https://github.com/aemsites/creditacceptance/issues/458)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/no-ssn-no-itin
- After: https://rparrish-mq-big2--creditacceptance--aemsites.aem.page/campaign/no-ssn-no-itin
Testing criteria - Look that the marquee height goes to 700 on desktop, Check the nav on logo-only pages that the brand logo is left aligned and account/hamburger icons are hidden on mobile.
=> Marquee `height-medium` && `height-large`

blocks/header/header.css, blocks/marquee/marquee.js, scripts/scripts.js, styles/styles.css
- addressed header center on desktop
- reduced margin on `divider-thin-blue-dot`
- wait for fontsLoaded before setting marquee intro border width
Fix 
- https://github.com/aemsites/creditacceptance/issues/458
- https://github.com/aemsites/creditacceptance/issues/462
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/about/contact-us
- After: https://rparrish-nav-line--creditacceptance--aemsites.aem.page/about/contact-us
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/no-ssn-no-itin
- After: https://rparrish-nav-line--creditacceptance--aemsites.aem.page/campaign/no-ssn-no-itin
Testing criteria - verify changes on branch
=> Header center desktopUp, `divider-thin-blue-dot`: margin reduce

blocks/header/header.css
There was some unclosed selectors that were overlooked causing the remaining styles to be omitted. 
Fix /na
Test URLs:
- After: https://rparrish-nav-fix--creditacceptance--aemsites.aem.page/
logo-only:
- Before: https://main--creditacceptance--aemsites.aem.page/campaign/prequalify
- After: https://rparrish-nav-fix--creditacceptance--aemsites.aem.page/campaign/prequalify
Testing criteria - Make sure the nav looks good in all viewports and when logo-only is used.
=> Nav display issue

blocks/marquee/animated/animated-toggle.css, blocks/marquee/marquee.js
CA noted the animated marquee border wasn't getting styled properly. The color on the border wasn't applied on switched state and the border width didn't follow the pattern where it goes the same width as the header. 
These issues are both addressed
Fix /na
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/purchase-program
- After: https://rparrish-mq-intro--creditacceptance--aemsites.aem.page/dealers/purchase-program
Testing criteria - Check that the border is styled on toggle w/ the correct color and is the width of the headline
=> Animated marquee - title border issue

blocks/anchor-links/anchor-links.css, blocks/feed/feed.css, blocks/tabs/tabs.css
- Addressed tabs list text-wrap - max-width and word wrap
- Fixed issue on the-lot page where tabs border was only applied on active and caused content shift
Fix https://github.com/aemsites/creditacceptance/issues/473
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/portfolio-program/details-100
- After: https://rparrish-tabs-wrap--creditacceptance--aemsites.aem.page/dealers/portfolio-program/details-100
the-lot URL: 
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/the-lot
- After: https://rparrish-tabs-wrap--creditacceptance--aemsites.aem.page/dealers/the-lot
Testing criteria - Confirm tabs list label text-wraps on smaller viewports.
=> Added tabs support for text-wrap

__tests__/anchor-links.test.js, __tests__/awards.test.js
Added test coverage for awards and anchor-links blocks.
Test URLs:
- After: https://lauryn-unit-tests--creditacceptance--aemsites.aem.page/
=> chore: jest testing to awards + anchor-links

styles/styles.css
- Added `row-gap-0` to section grid styles
FYI - I only added row-gap-0 for now... If more options are needed in the future we can add them then. Ex. `row-gap-3` OR `col-gap-3` etc. 
Fix https://github.com/aemsites/creditacceptance/issues/488
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/about/contact-us
- After: https://rparrish-row-gap--creditacceptance--aemsites.aem.page/about/contact-us
Testing criteria - check the page on mobile and confirm the `row-gap` is 0 on the grid content in the 'Location & Holiday closures` section
=> Added grid row-gap-0 style

blocks/columns/columns.css, styles/styles.css
- Added new grid gap variants that are scalable in different viewports. #496 
`gap-m` = `2rem / 5rem` (mobile, tablet / big desktop [>1200])
`gap-l` = `3rem / 6rem` (mobile, tablet / big desktop [>1200])
- Included support for big-icons h3 headers to have inline margin. (same as h4) #497
Fix https://github.com/aemsites/creditacceptance/issues/496 && https://github.com/aemsites/creditacceptance/issues/497
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/join-our-network
- After: https://rparrish-grid-gaps--creditacceptance--aemsites.aem.page/dealers/join-our-network
- Check in tablet viewport that the content doesn't go outside the grid column area
- Check in mobile viewport that the first big-icon headline is properly indented and doesn't …
=> Added grid gap variants `gap-m` & `gap-l` and Fixed big-icon headlines to support h3 tags

blocks/cards/cards.css
Fix #514 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane/financial-education
- After: https://smalla-514--creditacceptance--aemsites.aem.page/car-buyers/express-lane/financial-education
Testing criteria - Cards shouldn't overflow the screen width in any viewport.
=> #514 - fix min grid item width

blocks/testimonials/testimonials.css
This gap issue was rather because of the position of the reviewer's details.
Fix #520 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/customers/reviews
- After: https://smalla-520--creditacceptance--aemsites.aem.page/customers/reviews
=> #520 - fix reviewer's detail alignment

blocks/header/header.css, blocks/header/header.js
Added a method to the nav-customers to denote a column division. This works by adding a list w/ `---` acting as a divider for menu items. 
Fix https://github.com/aemsites/creditacceptance/issues/510
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/rparrish/
- After: https://rparrish-nav-order--creditacceptance--aemsites.aem.page/drafts/rparrish/
Testing criteria - Check that the menu item columns get authored by the method above. 
Note: this will require a small authoring adjustment to the nav menu items.
=> Nav-customers submenu out of order

blocks/accordion/accordion.css, blocks/columns/columns.css
Columns `.bg-shape-right` has overflow, reduced radius & padding
accordion.arrow heading with paragraph and icon
Fix https://github.com/aemsites/creditacceptance/issues/540
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/accordions
- After: https://rparrish-accord--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/accordions
HP
- After: https://rparrish-accord--creditacceptance--aemsites.aem.page/
Testing criteria - what should the reviewer look for in your PR:
test this branch on other known uses of accordion blocks to check for regression
=> Columns .bg-shape-right update and Accordion title w/ paragraphs in .arrow type

blocks/modal/modal.css
Fix for modal close button being overlapped by the video content 
Fix #545 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/resources
- After: https://nrego-modal-close--creditacceptance--aemsites.aem.page/car-buyers/resources
Testing criteria - a user should be able to clearly see and use the close button on the modal
=> [#545] Modal close button overlapped by content

blocks/accordion/accordion.css, blocks/columns/columns.css
- made accordion summary paragraphs normal text color
- added row-gap 1-4 on columns
Fix: https://github.com/aemsites/creditacceptance/issues/540
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/accordions
- After: https://rparrish-accord-fix--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/accordions
Testing criteria - check you can author `row-gap-2` etc. Make sure accordion summary `<p>` tags are `text-color`
=> Accordion summary paragraph color, column row-gap styles

blocks/anchor-links/anchor-links.css, styles/styles.css
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #535 
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/about/contact-us
- After: https://nrego-dot-dividers--creditacceptance--aemsites.aem.page/about/contact-us
Testing criteria - dots should be smaller in size.
Additional testing urls: 
- Before: https://main--creditacceptance--aemsites.aem.page/dealers/resources
- After: https://nrego-dot-dividers--creditacceptance--aemsites.aem.page/dealers/resources
=> [#535] Divider dots too long

blocks/columns/columns.css
In the [columns] block there is a variant `media-unbound` which allows the image to go outside the page margins to meet up w/ the window edge. This image calculation does a simple 50vw which puts it outside the viewport and some image cropping is happening. 
- adjusted this `<picture>` width calculation to be `100% relative column width + page gutter space` to accurately measure the width.
- added another optional variant `media-contain` which sets this image to be `object-fit: contain` rather than the default `cover`
Fix https://github.com/aemsites/creditacceptance/issues/515
Test URLs:
- After: https://rparrish-col-img--creditacceptance--aemsites.aem.page/
https://rparrish-col-img--creditacceptance--aemsites.aem.page/car-buyers …
=> Columns `media-unbound` image clipping issue fixed and added a `media-contain` variant

blocks/columns/columns.css, blocks/columns/columns.js, blocks/jon-representative/jon-representative.js
Adds support to the [columns] block for combo variants `media-unbound, media-contain` 
This will display media w out the image getting clipped and scales the column height to the relative media height on `<960` viewports.  
Fix [#515](https://github.com/aemsites/creditacceptance/issues/515)
Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/columns
- After: https://rparrish-col-img-scale--creditacceptance--aemsites.aem.page/drafts/jpetersen/regression/columns
HOME URLs:
- After: https://rparrish-col-img-scale--creditacceptance--aemsites.aem.page/
Testing criteria - Confirm these variants work as expected and no regression or display issues are seen across any usage
=> Columns `media-unbound, media-contain` display issues

blocks/columns/columns.js
Test URLs:
- After: https://mediafix--creditacceptance--aemsites.aem.page/
Details:
Setting media height was only triggered on resize. Changes made to trigger that on page load.
=> Media height on load
